### PR TITLE
Add: Color Palette to MUI Theme

### LINKED ISSUE #13: Menentukan Color Palette
# Saran Color Palette
Color Palette yang akan digunakan adalah Color Palettenya Material Design 2
Untuk lebih jelasnya bisa buka link berikut https://m2.material.io/design/color/the-color-system.html#color-theme-creation

## Contoh Material Design 2's Color Palette:
Material Design 2's Color Palette

## List warna:
- Primary (Warna utama)
- On Primary (Warna komponen yang berada di atas warna Primary, misalnya seperti teks)
- Light Primary (Versi terangnya warna Primary)
- Dark Primary (Versi gelapnya warna Primary)
- Secondary (Warna kedua)
- On Secondary (Warna komponen yang berada di atas warna Secondary, misalnya seperti teks)
- Light Secondary (Versi terangnya warna Secondary)
- Dark Secondary (Versi gelapnya warna Secondary)
- Background (Warna background)
- On Background (Warna komponen yang berada di atas warna Background, misalnya seperti teks)
- Surface (Warna untuk komponen-komponen seperti card, sheet, dan menu.
- On Surface (Warna komponen yang berada di atas warna Surface, misalnya seperti teks)
- Error (Warna jika action gagal, misalnya ketika Project Manager gagal menambahkan Task karena database down)
- On Error (Warna komponen yang berada di atas warna Error, misalnya seperti teks)
- Success (Warna jika action sukes, misalnya ketika Project Manager berhasil menambahkan Task)
- On Succes (Warna komponen yang berada di atas warna Success, misalnya seperti teks)

## Komen dengan menggunakan format berikut:
| Color Name | Color Hex |
| - | - |
| Primary | \<hex> |
| On Primary | <hex(#FFFFFF, #000000)> |
| Light Primary | <hex, nullable> |
| Dark Primary | <hex, nullable> |
| Secondary | \<hex> |
| On Secondary | <hex(#FFFFFF, #000000)> |
| Light Secondary | <hex, nullable> |
| Dark Secondary | <hex, nullable> |
| Background | <hex, default = #FFFFFF> |
| On Background | <hex(#FFFFFF, #000000)> |
| Surface | <hex, default = #FFFFFF> |
| On Surface | <hex(#FFFFFF, #000000)> |
| Error | \<hex, default = #D32F2F> |
| On Error | <hex(#FFFFFF, #000000)> |
| Success | \<hex, default = #4CAF50> |
| On Success | <hex(#FFFFFF, #000000)> |

## Contoh:
| Color Name | Color Hex |
| - | - |
| Primary | #6200EE |
| On Primary | #FFFFFF
| Light Primary | null |
| Dark Primary | #3700B3 |
| Secondary | #03DAC6 |
| On Secondary | #000000 |
| Light Secondary | null |
| Dark Secondary | #018786 |
| Background | #FFFFFF |
| On Background | #000000 |
| Surface | #FFFFFF |
| On Surface | #000000 |
| Error | #D32F2F |
| On Error | #FFFFFF |
| Success | #4CAF50 |
| On Success | #FFFFFF |

### PR DESCRIPTION
**Pull request by mdaffailhami**
# Resolve #13 Menentukan Color Palette

Colors

| Color Name | Color Hex |
| - | - |
| Primary | #1976D2 |
| On Primary | #FFFFFF |
| Light Primary | #1E88E5 |
| Dark Primary | #1565C0 |
| Secondary | #757575 |
| On Secondary | #FFFFFF |
| Light Secondary | #BDBDBD |
| Dark Secondary | #424242 |
| Background | #FFFFFF |
| On Background | #000000 |
| Surface | #FFFFFF |
| On Surface | #000000 |
| Error | #D32F2F |
| On Error | #FFFFFF |
| Success | #2E7D32 |
| On Success | #FFFFFF |

### CODE REVIEW

**Review by bhaktiramadhani — APPROVED** [review]
mantapp

**Review by afifabroory — CHANGES_REQUESTED** [review]
Add theme.js nya aja bisa nggak? WKwk

**Comment by mdaffailhami** [comment]
> @afifabroory: Add theme.js nya aja bisa nggak? WKwk

theme.js tuh diimport ke App.js buat ngebungkus semua Component, jadi App.js tetap harus diedit

**Comment by afifabroory** [comment]
> > @afifabroory: Add theme.js nya aja bisa nggak? WKwk
> 
> theme.js tuh diimport ke App.js buat ngebungkus semua Component, jadi App.js tetap harus diedit

Iya, tadi ketinggalan. Sisain theme.js sama App.js. Homepage.js nggak usah

**Comment by mdaffailhami** [comment]
> > > @afifabroory: Add theme.js nya aja bisa nggak? WKwk
> > 
> > 
> > @mdaffailhami: theme.js tuh diimport ke App.js buat ngebungkus semua Component, jadi App.js tetap harus diedit
> 
> @afifabroory: Iya, tadi ketinggalan. Sisain theme.js sama App.js. Homepage.js nggak usah

Okeh 👌️

**Comment by mdaffailhami** [comment]
> > > @afifabroory: Add theme.js nya aja bisa nggak? WKwk
> > 
> > 
> > @mdaffailhami: theme.js tuh diimport ke App.js buat ngebungkus semua Component, jadi App.js tetap harus diedit
> 
> @afifabroory: Iya, tadi ketinggalan. Sisain theme.js sama App.js. Homepage.js nggak usah

Dah direvert 👍️

**Review by afifabroory — APPROVED** [review]
Approve 👍

**Pull request merged**
